before_install:
- ${BEFORE_INSTALL}
before_script:
- cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
- bundle exec rake db:setup
bundler_args: --without $BUNDLER_INSTALL_WITHOUT
cache: bundler
env:
  matrix:
  - BUNDLER_INSTALL_WITHOUT="sqlite3" RAKE_TASKS="spec" SPEC_OPTS="--tag auxiliary --tag encoder --tag exploit --tag nop --tag post"
  - BEFORE_INSTALL="./travis-ci/install_sqlite3" CPATH="${PWD}/output/include" BUNDLER_INSTALL_WITHOUT="postgresql" LD_LIBRARY_PATH="${PWD}/output/lib" LIBRARY_PATH="${PWD}/output/lib" RAKE_TASKS="spec" SPEC_OPTS="--tag auxiliary --tag encoder --tag exploit --tag nop --tag post"
  - BEFORE_INSTALL="./travis-ci/install_sqlite3" CPATH="${PWD}/output/include" BUNDLER_INSTALL_WITHOUT="postgresql" LD_LIBRARY_PATH="${PWD}/output/lib" LIBRARY_PATH="${PWD}/output/lib" RAKE_TASKS="spec" SPEC_OPTS="--tag payload_single --tag payload_stage --tag payload_staged --tag payload_stager"
  - BUNDLER_INSTALL_WITHOUT="sqlite3" RAKE_TASKS="spec" SPEC_OPTS="--tag payload_single --tag payload_stage --tag payload_staged --tag payload_stager"
  - BUNDLER_INSTALL_WITHOUT="sqlite3" RAKE_TASKS="spec cucumber coverage" SPEC_OPTS="--tag ~content"
  - BEFORE_INSTALL="./travis-ci/install_sqlite3" CPATH="${PWD}/output/include" BUNDLER_INSTALL_WITHOUT="postgresql" LD_LIBRARY_PATH="${PWD}/output/lib" LIBRARY_PATH="${PWD}/output/lib" RAKE_TASKS="spec cucumber coverage" SPEC_OPTS="--tag ~content"
  - BUNDLER_INSTALL_WITHOUT="postgresql" RAKE_TASKS="yard:stats"
  - BUNDLER_INSTALL_WITHOUT="sqlite3" RAKE_TASKS="yard:stats"
  global:
    secure: cOCoUB1zTvnl274EftNxbbmkL8MIlXa9a2/NLXpJFfJaL39JLYLCvrj85ndLO75fl8W5j7Xnx1w3kyNCL0FUumWzrIfcJFwTADv20EggrmrrJaEJDdqi3+oxFA8/AHQK7GUXws2AEhbs1ujXO7wA44qeQmO1daWdbXmN5t2qoxc=
language: ruby
matrix:
  fast_finish: true
rvm:
- 2.1
script: bundle exec rake $RAKE_TASKS
sudo: false
