env:
  matrix:
  - RAKE_TASK=spec
  global:
    secure: cOCoUB1zTvnl274EftNxbbmkL8MIlXa9a2/NLXpJFfJaL39JLYLCvrj85ndLO75fl8W5j7Xnx1w3kyNCL0FUumWzrIfcJFwTADv20EggrmrrJaEJDdqi3+oxFA8/AHQK7GUXws2AEhbs1ujXO7wA44qeQmO1daWdbXmN5t2qoxc=
language: ruby
matrix:
  allow_failures:
  - rvm: 2.2
  - rvm: jruby-head
  - rvm: ruby-head
  fast_finish: true
  include:
  - rvm: 2.1
    env: RAKE_TASK=yard
rvm:
- 1.9.3
- 2.0
- 2.1
- 2.2
- ruby-head
- jruby-1.7.18
- jruby-head
- rbx
script: bundle exec rake $RAKE_TASK
